version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  postgres_admin:
    container_name: postgres_admin
    image: 'dpage/pgadmin4'
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin
