version: '3'

services:
  flyway:
    container_name: flyway_postgres
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
    command: migrate
